keys add <name> was missing
Otherwise user will get:

 docker run --rm \
>     --interactive \
>     --tty \
>     --volume ${HOME}/.sentinelnode:/root/.sentinelnode \
>     sentinel-dvpn-node process keys add
Error: invalid section keyring: from cannot be empty